Go_cart/urls.py
from django.conf import settings
from django.conf.urls import  url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from shop.views import product_list,product_detail
from search.views import do_search
from customer_care.views import contact
from upload.views import upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carts/',include('carts.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='account')),
    path('',include('shop.urls',namespace='shop')),
    path('query',do_search,name='search'),
    path('contact',contact,name='contact'),
    path('upload',upload,name='upload'),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import  url


app_name='cart'
from .views import (
 cart_update,
cart_remove,
 cart_home,
 checkout_home,
 checkout_done_view,
handlerequest,
SendtoPaytm,
fav_update,
fav_home,
fav_remove,
)
urlpatterns = [

    url(r'^$', cart_home,name='home' ),
    url(r'^checkout/S', checkout_home, name='checkout'),
    url(r'^update/$',cart_update,name='update' ),
    url(r'^remove/$',cart_remove,name='remove' ),
    url(r'^fav/$', fav_home,name='favourite' ),
    url(r'^fav/update/$',fav_update,name='fav_update' ),
    url(r'^fav/remove/$',fav_remove,name='fav_remove' ),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^handlerequest/$', handlerequest, name='HandleRequest'),
    url(r'^paymentgateway/$', SendtoPaytm, name='Paytm'),
    url(r'^coupon/$', fav_home,name='coupon_apply' ),
]

shop/urls.py
from django.urls import path
from django.conf.urls import  url
from .import views

app_name='shop'

urlpatterns=[
    path('', views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
]

carts/models.py
from django.conf import settings
from django.db import models
from shop.models import Product
from django.db.models.signals import pre_save,post_save,m2m_changed
User = settings.AUTH_USER_MODEL
# Create your models here.


class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id = request.session.get("cart_id", None)

        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj,new_obj

    def new(self,user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User,null=True,blank=True ,on_delete=models.CASCADE)
    products =  models.ManyToManyField(Product,blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total  = models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    order_id = models.CharField(max_length=15,blank=True,null=True)
    updates = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

class FavManager(models.Manager):
    def new_or_get(self,request):
        fav_id = request.session.get("fav_id", None)

        qs = self.get_queryset().filter(id=fav_id)
        if qs.count() == 1:
            new_obj = False
            fav_obj = qs.first()
            if request.user.is_authenticated and fav_obj.user is None:
                fav_obj.user = request.user
                fav_obj.save()
        else:
            fav_obj = Favourite.objects.new(user=request.user)
            new_obj = True
            request.session['fav_id'] = fav_obj.id
        return fav_obj,new_obj

    def new(self,user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Favourite(models.Model):
    user = models.ForeignKey(User,null=True,blank=True ,on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)

    objects = FavManager()

    def __str__(self):
        return str(self.user.email)



def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
    if action== 'post_add' or action== 'post_remove' or action== 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        #print(total)
        instance.subtotal = total
        instance.save()


m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)

def pre_save_cart_receiver(sender,instance,*args,**kwargs):
    instance.total = instance.subtotal ##here we can multiply each subtotal with taxes or shipping charge
pre_save.connect(pre_save_cart_receiver,sender=Cart)

carts/views.py
from django.shortcuts import render,redirect,HttpResponse,reverse, get_object_or_404
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .Checksum import verify_checksum,generate_checksum
from .utils import random_string_generator
from django.contrib import messages
import http.client as ht
from order.models import Order,Order_Count


# Create your views here.
# def cart_create(user=None):
#     cart_obj = Cart.objects.create(user=None)
#     return cart_obj
MERCHANT_KEY = 'kbzk1DSbJiV_O3p5';
from shop.models import Product,Coupon
from .models import Cart,Favourite


def cart_home(request):
    return render(request, "carts/home.html")


def cart_update(request):
    id = request.POST.get('product_id')
    quantity = int(request.POST.get('quantity'))

    cart = request.session.get('cart', {})

    cart[id] = cart.get(id, quantity)
    
    request.session['cart'] = cart
    messages.info(request, "Item added to Cart")
    return redirect(reverse('shop:product_list'))


def cart_remove(request):
    id = request.POST.get('item_id')
    quantity = int(request.POST.get('quantity'))
    cart = request.session.get('cart', {})

    if quantity > 0:
        cart[id] = quantity
    else:
        cart.pop(id)

    request.session['cart'] = cart
    return redirect(reverse('cart:home'))

def fav_home(request):
    fav_obj,new_obj = Favourite.objects.new_or_get(request)
    return render(request, "carts/favourite.html", {"fav":fav_obj})


def fav_update(request):
    print("aa gye fav mai update")
    product_id = request.POST.get("product_id")
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Product is gone")
            return redirect("shop:product_list")
        fav_obj, new_obj = Favourite.objects.new_or_get(request)

        fav_obj.products.add(product_obj)
            #added = True
    return redirect("shop:product_list")  #redirecting using namespace feature




def fav_remove(request):
    product_id = request.POST.get("product_id")
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Product is gone")
            return redirect("cart:home")
        fav_obj, new_obj = Favourite.objects.new_or_get(request)
        if product_obj in fav_obj.products.all():
            fav_obj.products.remove(product_obj)

    return redirect("cart:favourite")  #redirecting using namespace feature


def checkout_home(request):
    order_id = random_string_generator()
    # qs = Cart.objects.filter(order_id=order_id)
    # if qs.exists():
    #     order_id = random_string_generator()
    return render(request, "carts/checkout.html",{'order_id':order_id,'newtotal':None,'flag':True})

def SendtoPaytm(request):
    param_dict = {}
    data = request.POST

    if request.POST.get('submit') == 'button3':
        coupons = Coupon.objects.all()
        order_id = request.POST.get('order_id')
        total = request.POST.get('total')
        return render(request,"carts/coupon.html",{'coupons':coupons,'order_id':order_id,'total':total})
    if request.POST.get('submit') == 'button4':
        code = request.POST.get('code')
        discount = Coupon.objects.filter(code=code)[0]
        order_id = request.POST.get('order_id')
        newtotal = float(request.POST.get('total')) - float(discount.discprice)
        return render(request, "carts/checkout.html",{'order_id':order_id,'newtotal':newtotal,'flag':False})

    try:
        numoforder = Order_Count.objects.get(email=data['email'])
        numoforder.Ordercount +=1
        numoforder.save()
    except:
        numoforder = Order_Count.objects.create(email=data['email'],Ordercount=1)

    if request.POST.get('submit')=='button1':
        paid = True
        newtotal = request.POST.get('newtotal')
        if newtotal != 'None':
            print("yes")
            total = newtotal
        param_dict = {
            'MID': 'WorldP64425807474247',
            'ORDER_ID': str(data['order_id']) ,
            'TXN_AMOUNT': str(float(total)),
            'CUST_ID': data['email'],
            'INDUSTRY_TYPE_ID': 'Retail',
            'WEBSITE': 'WEBSTAGING',
            'CHANNEL_ID': 'WEB',
            'CALLBACK_URL': 'https://rainbowcart.herokuapp.com/carts/handlerequest/', #'http://127.0.0.1:8000/carts/handlerequest/', #
        }

        details = request.session['items']
        obj = Order.objects.create(username=request.user, order_id=str(data['order_id']), address=data['address'],total=str(float(total)),
                                   contact=data['contact'],email=data['email'],paid=True,details= details)
        param_dict['CHECKSUMHASH'] = generate_checksum(param_dict, MERCHANT_KEY)
        cart = {}
        request.session['cart'] = cart

        return render(request, 'carts/paytm.html', {'param_dict': param_dict})
    if request.POST.get('submit') == 'button2':
        cart_obj,new_obj=Cart.objects.new_or_get(request)
        order_id=request.POST.get('order_id')
        address=request.POST.get('address')
        contact = request.POST.get('contact')
        email = request.POST.get('email')
        total = request.POST.get('total')
        newtotal = request.POST.get('newtotal')
        print(newtotal,type(newtotal))
        if newtotal !='None':
            print("yes")
            total = newtotal

        details = request.session['items']
        obj = Order.objects.create(username=request.user, order_id=str(data['order_id']), address=data['address'],
                                   total=str(float(total)), contact=data['contact'],email=email,paid=False,details= details)
        cart = {}
        request.session['cart'] = cart
        return render(request, "carts/cashondel.html",{'total':total,'address':address,'contact':contact,'order_id':order_id})


        

@csrf_exempt
def handlerequest(request):
    form = request.POST
    response_dict = {}
    for i in form.keys():
        response_dict[i] = form[i]
        if i=='CHECKSUMHASH':
            checksum = form[i]
    verify = verify_checksum(response_dict,MERCHANT_KEY,checksum)
    if verify:
        if response_dict['RESPCODE']=='01':
            print("Order Successful")
        else:
            print('Order was not Successful'+response_dict['RESPMSG'])
            order_id = response_dict['ORDERID']
            obj = Order.objects.filter(order_id=order_id)[0]
            obj.paid=False
            obj.save()
    return render(request,'carts/paymentstatus.html',{'response':response_dict})


def send_sms():
    conn = ht.HTTPSConnection("api.msg91.com")

    payload = '''{
      "sender": "RNBWCT",
      "route": "4",
      "country": "91",
      "sms": [
        {
          "message": "Hello you won",
          "to": [
            "9511531960"
          ]
        }
      ]
    }'''
    headers = {
        'authkey': "316162A2MenzoRsCJ55e3559d1P1",
        'content-type': "application/json"
    }

    conn.request("POST", "/api/v2/sendsms", payload, headers)

    res = conn.getresponse()
    data = res.read()

    print(data.decode("utf-8"))



def checkout_done_view(request):
    return render(request, "carts/checkout-done.html")

carts/templates/carts/cashondel.html
{% extends 'base.html' %}

{% block content  %}
    <h2 style="color: #1c7430;"><b>Your Order Has Been Placed Successfully</b></h2>
<h5><b>Order ID: {{ order_id}}</b></h5>


<h2>Order details:</h2>


<table class="table table-borderless">

  <tbody>
    <tr>
      <td>Name:</td>
      <td>{{ user }}</td>
    </tr>
    <tr>
      <td>Contact Number:</td>
      <td>{{ contact }}</td>
    </tr>

    <tr>
      <td>Shipping Address:</td>
      <td>{{ address }}</td>
    </tr>
    <tr>
      <td>Total Amount</td>
      <td>{{ total }}</td>
    </tr>
  </tbody>
</table>




{% endblock %}

carts/templates/carts/checkout-done.html
{% extends 'base.html' %}



{% block content %}
<div class="col-6 mx-auto py-5 text-center">
    <h1 class="display-1">Thank you for your order!!!</h1>
</div>
{% endblock %}

carts/templates/carts/checkout.html
{% extends 'base.html' %}
<style>
   .pbox{
       background-color: rgba(183,188,125,0.73);
   }
</style>


{% block content %}
<strong>Order Id : {{ order_id }} </strong>
<h1>Finalize Checkout</h1>
    <br>
<div class="container">

  <div class="row">
    <div class="col-sm-2" style="background-color: rgba(188,176,188,0.73) ">

      <h3 style="text-align: center"><b>Items:</b> </h3>
        {% for item in cart_items %}
        <ul>
            <li>
                <h5 >{{ item.product.name }}</h5>
            </li>
        </ul>

        {%if not forloop.last %}
        {% endif %}
        {% endfor %}

    </div>




  <div class="col-sm-3">
  </div>
    <div class="col-sm-5">
      <form class="form" method ="POST" action="{% url 'cart:Paytm' %}">{% csrf_token %}
          <input type="hidden" name="order_id" value="{{order_id}}">

          <input type="hidden" name="total" value="{{total}}">
          <input type="hidden" name="newtotal" value="{{ newtotal}}">




<!--          <input type="hidden" name="cart_id" value="{{object.id}}">-->
          <table class="table table-striped">
              <tbody>
              <tr>
                  <td>Shipping Address:</td>
                  <td><input type="text" width="50px" height="50px" name="address" required></td>
              </tr>
              <tr>
                  <td>Email:</td>
                  <td><input type="email" name="email" required></td>
              </tr>
                <tr>
                  <td>Contact Number:</td>
                  <td><input minlength="10"  maxlength="10" type="tel" name="contact" required></td>
              </tr>
              <tr>
                  <td>Cart Total:</td>
                  <td>{{ total }}</td>
              </tr>


              <tr>
                  <td>Shipping Total:</td>
                  <td></td>
              </tr>
              <tr>
                  <td>Order Total:</td>
                  {% if newtotal %}
                  <td>{{ newtotal }}</td>
                  {% else %}
                  <td>{{ total }}</td>
                  {% endif %}
              </tr>
              </tbody>

          </table>


        <button type="submit" name="submit" value="button1">Pay Now</button>
          <button type="submit" name="submit" value="button2">Cash On Deleivery</button>

        </form>
        <hr>
    <form class="form" method ="POST" action="{% url 'cart:Paytm' %}">{% csrf_token %}
          <input type="hidden" name="order_id" value="{{order_id}}">
            <input type="hidden" name="total" value="{{total}}">
        {% if flag %}
          <button type="submit" name="submit" value="button3">Apply Coupon</button>
        {% endif %}
        </form>


    </div>
  </div>
</div>


{% endblock %}

carts/templates/carts/coupon.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
#rcorners1 {
    border: 1px solid #062c33;
  border-radius: 10px;
    border-collapse: separate;
    margin-right: 20px;
    margin-bottom: 20px;
  border-spacing: 15px 50px;
    background: rgba(70,89,29,0.02);
  padding: 20px;
  width: 350px;
  height: 150px;
}
    </style>



<br><br>
    <div class="container" align="center">
    <h2><strong>Coupons</strong></h2>
    </div>
    <br><br>

    <div class="container">
  <div class="row">
    {% for c in coupons %}
      <div id="rcorners1" class="col-sm-4 ">
      <h4 style="color: #0f6674" align="center"><strong>Coupon Code: {{ c.code }}</strong></h4>
          <br>

          <p>{{ c.description }}</p>
    </div>
{% endfor %}
  </div>
    </div>

<form method="POST" action="{% url 'cart:Paytm' %}">{% csrf_token %}
    <input type="hidden" name="order_id" value="{{order_id}}">
    <input type="hidden" name="total" value="{{total}}">

            <input  type="text"   name="code" placeholder="Type here" >
            <button type="submit" name="submit" value="button4" class="btn btn-primary">Apply</button>
            </form>


{% endblock %}

carts/templates/carts/favourite.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container" align="center">
    <h2><strong>Favourites </strong></h2>
</div>

    <div class="row row-flex">
        {% for product in fav.products.all  %}

            <div class="col-xs-10 col-xs-offset-1 col-sm-offset-0 col-sm-3 col-md-3 display panel panel-defualt ">

                <div class="panel-body">
                    <div class="product" align="center"><img  width="200" height="150"; src="{{ product.image1 }}"></div>
                    <br>
                    <h3 class="text-center"><b>{{ product.name }}</b></h3>
                    <p class="product-description text-center">{{ product.description }}</p>
                    <p class="text-center">Price = ₹ {{ product.price }}/-</p>



                    <form class='form' method="post" action="{% url 'cart:fav_remove' %}">
                        <input type="hidden" name="product_id" value ={{ product.id }}>
                        {% csrf_token %}
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <button  class="btn btn-danger" type="submit">Remove</button>

                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html' %}
{% block content %}

<h1> CART</h1>
{% if length  %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Image</th>
            <th></th>
          <th>Product Price</th>

        </tr>
      </thead>
      <tbody class="cart-body">
      {% for item in cart_items %}
        <tr class='cart-product'>
          <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{{item.product.get_absolute_url }}"> <img height="130" width="130" src={{ item.product.image1 }}></a>
            <br>
                <h4>{{ item.product.name }} </h4>
            </td>
          <td>
          <form class="form-inline" method="post" action="{% url 'cart:remove' %}">
              <input type="hidden" name="item_id" value ={{ item.id }}>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputAmount" class="sr-only">New Qty</label>
                        <div class="input-group">
                            <div class="input-group-addon">Qty</div>
                            <input name="quantity" type="number" min="0" max="{{ item.product.stock }}" class="form-control" required>
                            <div class="input-group-addon">{{ item.quantity }}</div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
          </form>
          </td>
          <td>{{ item.product.price }}</td>

        </tr>
      {% endfor %}
        <tr>
          <td  colspan="2" ></td>
            <td></td>
            <td><b>Subtotal</b> ₹ &nbsp; <span class='cart-subtotal'>{{ total }}</span></td>
        </tr>
      <tr>
          <td colspan="2"></td>
          <td></td>
            <td><b>Total</b> ₹ &nbsp;<span class='cart-total'> {{ total }}</span></td>
      </tr>
      <tr>
          <td colspan="2"></td>
          <td><a href="{% url 'shop:product_list' %}">ADD MORE PRODUCTS</a></td>
          <td><a class="btn btn-lg btn-success" href="{% url 'cart:checkout' %}">Checkout</a> </td>

      </tr>
      </tbody>
    </table>




{% else %}
<p class="lead"> Cart is empty</p>
    <h5><a href="{% url 'shop:product_list' %}">shop</a></h5>
{% endif %}
{% endblock %}

carts/templates/carts/paymentstatus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Payment status regarding your order ID : {{ response.ORDERID }}</h2>
{% if response.RESCODE == '01' %}
<strong>ORDER SUCCESS</strong>
{% else %}
<strong>ORDER FAILED</strong>
{% endif %}
</body>
</html>

carts/templates/carts/paytm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Paytm merchant payment page</title>
</head>
<body>
<h1>Redirecting you to the merchant.Please do not refresh the page...</h1>
<form action="https://securegw-stage.paytm.in/order/process" method="POST" name="paytm">
    {% for key,value in param_dict.items %}
    <input type="hidden" name="{{key}}" value="{{value}}">
    {% endfor %}
</form>
</body>
<script>
    document.paytm.submit()
</script>
</html>

carts/templates/carts/remove.html
<form class='form-product' method='POST' action="{% url 'cart:remove' %}"  class="form">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }} ">
    <button type="submit" class="btn btn-link btn-sm" style="padding: 0px;cursor: pointer;"><h3>Remove? </h3>
    </button>
</form>