Go_cart/urls.py
from django.conf import settings
from django.conf.urls import  url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from shop.views import product_list,product_detail
from search.views import do_search
from customer_care.views import contact
from upload.views import upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('carts/',include('carts.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='account')),
    path('',include('shop.urls',namespace='shop')),
    path('query',do_search,name='search'),
    path('contact',contact,name='contact'),
    path('upload',upload,name='upload'),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.conf.urls import  url


app_name='cart'
from .views import (
 cart_update,
cart_remove,
 cart_home,
 checkout_home,
 checkout_done_view,
handlerequest,
SendtoPaytm,
fav_update,
fav_home,
fav_remove,
)
urlpatterns = [

    url(r'^$', cart_home,name='home' ),
    url(r'^checkout/S', checkout_home, name='checkout'),
    url(r'^update/$',cart_update,name='update' ),
    url(r'^remove/$',cart_remove,name='remove' ),
    url(r'^fav/$', fav_home,name='favourite' ),
    url(r'^fav/update/$',fav_update,name='fav_update' ),
    url(r'^fav/remove/$',fav_remove,name='fav_remove' ),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^handlerequest/$', handlerequest, name='HandleRequest'),
    url(r'^paymentgateway/$', SendtoPaytm, name='Paytm'),
    url(r'^coupon/$', fav_home,name='coupon_apply' ),
]

shop/urls.py
from django.urls import path
from django.conf.urls import  url
from .import views

app_name='shop'

urlpatterns=[
    path('', views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])



class Subcategory(models.Model):
    name=models.CharField(max_length=200,null=True,blank=True)
    slug=models.SlugField(max_length=200,null=True,blank=True)
    Category = models.ForeignKey(Category, related_name='categories', on_delete=models.CASCADE, null=True,
                                    blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='subcategory'
        verbose_name_plural='subcategories'
    def __str__(self):
        return self.name



class Brand(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)
    class Meta:
        ordering=('name',)
        verbose_name='brand'
        verbose_name_plural='brands'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])



class Product(models.Model):
    category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    brand=models.ForeignKey(Brand,related_name='products',on_delete=models.CASCADE,default=None)
    name=models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    hide_slug = models.IntegerField(default=0)
    image1 = models.CharField(max_length=500,blank=True,null=True)
    image2 = models.CharField(max_length=500, blank=True, null=True)
    image3 = models.CharField(max_length=500, blank=True, null=True)
    image4 = models.CharField(max_length=500, blank=True, null=True)
    image5 = models.CharField(max_length=500, blank=True, null=True)
    image6 = models.CharField(max_length=500, blank=True, null=True)
    image7 = models.CharField(max_length=500, blank=True, null=True)
    image8 = models.CharField(max_length=500, blank=True, null=True)
    image9 = models.CharField(max_length=500, blank=True, null=True)
    image10 = models.CharField(max_length=500, blank=True, null=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,default=0.00)
    mrp = models.DecimalField(max_digits=10, decimal_places=2,default=0.00)
    stock=models.IntegerField(default=True)
    available = models.BooleanField(default=True)
    LBH = models.TextField(max_length=50,null=True,blank=True,)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    qty = models.IntegerField(default=0)


    class Meta:
        ordering=('name',)
        index_together=(('id','slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])

class Coupon(models.Model):
    code = models.CharField(max_length=8,null=True,blank=True)
    description = models.CharField(max_length=200,null=True,blank=True)
    discprice = models.IntegerField(default=0,null=True,blank=True)

    def __str__(self):
        return self.code

shop/views.py
from django.shortcuts import render ,get_object_or_404
from .models import Category ,Product
from carts.models import Cart
#from cart.forms import CartAddProductForm

# Create your views here.
def product_list(request ,category_slug = None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_obj,new_obj = Cart.objects.new_or_get(request)
    if category_slug:
        category = get_object_or_404(Category ,slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'list.html', {'category':category, 'categories':categories,'products':products})

def product_detail(request,id,slug):
    product=get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    
  #  cart_product_form=CartAddProductForm()
    return render(request, 'detail.html', {'product':product})

shop/templates/carousel.html
<div class="row">
    <h4>Get Social With Us</h4>
    <div id="social">
        <a class="facebookBtn smGlobalBtn" href="https://www.facebook.com/pages/Bigbasketcom/139311472851666" target="_blank"></a>
        <a class="pinterestBtn smGlobalBtn" href="https://in.pinterest.com/bigbasketcom/" target="_blank"></a>
        <a class="twitterBtn smGlobalBtn" href="https://twitter.com/Bigbasket_com" target="_blank"></a>
        <a class="instagramBtn smGlobalBtn" href="https://www.instagram.com/bigbasketcom/" target="_blank"></a>
    </div></div>

shop/templates/detail.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block content %}

<head>
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>jQuery exzoom: Product Carousel Example</title>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script src="https://www.jqueryscript.net/demo/Product-Carousel-Magnifying-Effect-exzoom/jquery.exzoom.js"></script>
    <link href="https://www.jqueryscript.net/demo/Product-Carousel-Magnifying-Effect-exzoom/jquery.exzoom.css" rel="stylesheet" type="text/css"/>
    <style>
    /* Popup container - can be anything you want */
.popup {
  position: relative;
  display: inline-block;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* The actual popup */
.popup .popuptext {
  visibility: hidden;
  width: 160px;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 8px 0;
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -80px;
}

/* Popup arrow */
.popup .popuptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

/* Toggle this class - hide and show the popup */
.popup .show {
  visibility: visible;
  -webkit-animation: fadeIn 1s;
  animation: fadeIn 1s;
}

/* Add animation (fade in the popup) */
@-webkit-keyframes fadeIn {
  from {opacity: 0;}
  to {opacity: 1;}
}

@keyframes fadeIn {
  from {opacity: 0;}
  to {opacity:1 ;}
}



#element1 {display:inline-block;margin-right:10px;}
#element2 {display:inline-block;}
    #exzoom {
        width: 400px;
        /*height: 400px;*/
    }

    .hidden { display: none; }
</style>
</head>

<body>

<div class="container">
<div class="row">

<div class="col-sm-6 " >
<div class="exzoom hidden" id="exzoom">
    <div class="exzoom_img_box">
        <ul class='exzoom_img_ul'>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
            <li><img src="{{ product.image1 }}"/></li>
        </ul>
    </div>
    <div class="exzoom_nav"></div>
    <p class="exzoom_btn">
        <a href="javascript:void(0);" class="exzoom_prev_btn"> < </a>
        <a href="javascript:void(0);" class="exzoom_next_btn"> > </a>
    </p>
</div>
</div>
    <div class="col-sm-2"></div>
<div class="col-sm-3">




       <img height="130" width="130" src="{% if product.image1 %}{{ product.image1 }}{% else %}{% static "img/no_image.png "%}{%endif  %}">
        <div class="caption">
            <h2>{{ product.name }}</h2>

            <h4><p class="product-description">{{ product.description }}</p></h4>
            <p>In Stock = {{ product.stock }}</p>
            MRP: <strike style="color: #1d2124;">₹{{ product.mrp }}</strike>
            <p>
            {% if product.LBH %}
            <p class="text-center"> Dimensions : {{ product.LBH }}</p>
            {% endif %}
            <h4 style="color: rgba(156,10,10,0.89)">Price:<b> ₹ {{ product.price }}</b></h4>
            <h4 id="element1">You Save:
                <h4 id="element2" style="color: rgba(156,10,10,0.89)"><b>₹</b></h4>
                <h4 id="element2" style="color: rgba(156,10,10,0.89)"><b><p id="demo"></p></b></h4>
                <h4 id="element2" style="color: rgba(156,10,10,0.89)"><b>(</b></h4>
                <h4 id="element2" style="color: rgba(156,10,10,0.89)"><b><p id="demo1"></p></b></h4>
                <h4 id="element2" style="color: rgba(156,10,10,0.89)"><b>%)</b></h4>
            </h4>
            <form method="post" action="{% url 'cart:fav_update' %}">
                        <input type="hidden" name="product_id" value ={{ product.id }}>
                        {% csrf_token %}
                <div class="popup" onclick="myFunction()">
                    <button type="submit" class="btn btn-link btn-sm" style="padding: 0px;cursor: pointer;"><h4>Add to Favourites</h4></button>
                    <span class="popuptext" id="myPopup">Product added to Favourites</span>
                </div>

            </form>
            <form method="post" action="{% url 'cart:update' %}">
                    <input type="hidden" name="product_id" value ={{ product.id }}>
                    {% csrf_token %}
                    <div class="input-group">
                        <input name="quantity" type="number"  min="1" max="{{ product.stock }}"  class="form-control" placeholder="Qty" required>
                        <span class="input-group-btn">
                            <button class="btn btn-success" type="submit">Add</button>
                        </span>
                    </div>
                </form>


        </div>
    </div>
</div>
</div>
<script type="text/javascript">

    $('.container').imagesLoaded( function() {
  $("#exzoom").exzoom({
        autoPlay: false,
    });
  $("#exzoom").removeClass('hidden')
});

</script>
<script>



var x = {{ product.mrp }}-{{ product.price }} ;
document.getElementById("demo").innerHTML = x;
var y = Number(x *100 /{{ product.mrp }});
var z = y.toFixed(0);
document.getElementById("demo1").innerHTML = z;

function myFunction() {
  var popup = document.getElementById("myPopup");
  popup.classList.toggle("show");
}
</script>
</body>


{% endblock %}

shop/templates/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}

<b>Products</b>
{% endblock %}
{% block content %}
<style>

img {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}

img:hover {
  box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
}
</style>
<div class='container' id="mydiv" align="center">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-3">
            {% if messages %}
            <div class="alert alert-success messages">
            {% for message in messages %}
            <span>
              {{ message }}
            </span>
            {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
<div class="row">
<br>
<br>
<div class="col-sm-2">
<div style=" padding:1px;
    border-radius: 8px;
   border:1px solid black;" id="sidebar">
    <h3 style="text-align: center;color: black ">Categories</h3><br>

    <ul>
        <li {% if not category %} class="selected"{% endif %}>
        <a style="color: #000;" href="{% url "shop:product_list" %}">All</a>
        </li>
    {% for c in categories %}
    <li {% if category.slug == c.slug %} class="selected"{% endif %}>
        <a style="color: black" href={{ c.get_absolute_url }}>{{ c.name }}</a>
        </li>
    {% endfor %}
    </ul>
<br>
<br>

</div>

<br>

<div style=" padding:1px;
    border-radius: 8px;
   border:1px solid black;" id="sidebar">
    <h3 style="text-align: center;color: black ">Delivery Time</h3><br>
       <div class="text-center">{% include 'timeslot/time.html' %}
       </div>
    <br>
    <br>
</div>

    <br>
    <br>








    </div>
<br>
<br>


<div class="col-sm-1"></div>
    <div class="col-sm-9">
<div class="row row-flex" >
        {% for product in products  %}

            <div    style="
   border:1px solid black;"   class="col-xs-10 col-xs-offset-1 col-sm-offset-0 col-sm-3 col-md-3 display panel panel-defualt ">

                <div class="panel-body">

<!--                    <div class="product" style="background-image: url('{{ product.image1 }}');width:230px;height:200px;"></div>-->
                        <div class="product" align="center"><a href="{{ product.get_absolute_url}}"><img width="200" height="150"; src="{{ product.image1 }}"></a></div>

                    <p class="text-center"><b>{{ product.name }}</b></p>
                    <strike><p class="text-center">₹ {{ product.mrp }}</p></strike>
                    <p class="text-center">Price:₹ {{ product.price }}/-</p>
                    {% if product.stock > 0 %}
                    <p class="text-center">In Stock: {{ product.stock }}</p>
                    {% else %}
                    <p class="text-center"><font color="red">Out of Stock</font> </p>
                    {% endif %}

                    <form method="post" action="{% url 'cart:update' %}">
                        <input type="hidden" name="product_id" value ={{ product.id }}>
                        {% csrf_token %}
                        <div class="input-group">
                            <input name="quantity" type="number" min="1" max="{{ product.stock }}" class="form-control form-size" placeholder="Qty" required>
                            <span class="input-group-btn">
                                <button class="btn btn-success" type="submit">Add</button>
                            </span>
                        </div>
                    </form>

                </div>
            </div>
        {% endfor %}
    </div>
    </div>
    </div>

     <section class="ftco-section">
			<div class="container">
				<div class="row no-gutters ftco-services">
          <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
            <div class="media block-6 services mb-md-0 mb-4">
              <div class="icon bg-color-1 active d-flex justify-content-center align-items-center mb-2">

                  <img style="height: 150px;width: 150px" src={% static 'images/Capture1.PNG' %}>
              </div>
              <div class="media-body">
                <h3 class="heading">Free Shipping</h3>
                <span>On order over ₹ 100</span>
              </div>
            </div>
          </div>
          <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
            <div class="media block-6 services mb-md-0 mb-4">
              <div class="icon bg-color-2 d-flex justify-content-center align-items-center mb-2">
            		<img style="height: 150px;width: 150px" src={% static 'images/Capture2.PNG' %}>
              </div>
              <div class="media-body">
                <h3 class="heading">Always Fresh</h3>
                <span>Product well package</span>
              </div>
            </div>
          </div>
          <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
            <div class="media block-6 services mb-md-0 mb-4">
              <div class="icon bg-color-3 d-flex justify-content-center align-items-center mb-2">
            		<img style="height: 150px;width: 150px" src={% static 'images/Capture3.PNG' %}>
              </div>
              <div class="media-body">
                <h3 class="heading">Superior Quality</h3>
                <span>Quality Products</span>
              </div>
            </div>
          </div>
          <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
            <div class="media block-6 services mb-md-0 mb-4">
              <div class="icon bg-color-4 d-flex justify-content-center align-items-center mb-2">
            		<img style="height: 150px;width: 150px" src={% static 'images/Capture4.PNG' %}>
              </div>
              <div class="media-body">
                <h3 class="heading">Support</h3>
                <span>24/7 Support</span>
              </div>
            </div>
          </div>
        </div>
			</div>
		</section>
    <br>
    <br>
<script>
    setTimeout(function() {
    $('#mydiv').fadeOut('fast');
    }, 800);
</script>
{% endblock %}